name: raspap

services:
  raspap:
    container_name: raspap
    image: ghcr.io/raspap/raspap-docker:latest
    restart: unless-stopped

    privileged: true
    network_mode: host

    environment:
      TZ: Europe/Madrid

    volumes:
      - /etc/raspap:/etc/raspap
      - /lib/modules:/lib/modules
      - /var/run/dbus:/var/run/dbus
      - /sys/class/net:/sys/class/net
